fs_user:
    resource: "@FSUserBundle/Resources/config/routing.yml"
    prefix:   /


fs_pays:
    resource: "@FSPaysBundle/Resources/config/routing.yml"
    prefix:   /maps

login:
    path: /login
    defaults:
        _controller: FSUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout