# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FS\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /maps
            remember_me:
                secret: %secret%


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/continent/continentlist, roles: ROLE_USER }
        - { path: ^/countrylist, roles: ROLE_USER }
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }

    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }