# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/login$
            anonymous: true
        register:
            pattern: ^/register/$
            anonymous: true

        main:
            fr3d_ldap: ~
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                remember_me: true
                default_target_path: /
            logout:       true
            anonymous:    true
            remember_me:
                secret:      %secret%
                lifetime: 604800 # 1 week in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
                secure:   true
                httponly: true

    access_control:
        - {path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/registring, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/admin, roles: ROLE_ADMIN}
