# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    my.listener:
        class: FS\PaysBundle\EventListener\UpdatePopulation
        tags:
            - { name: doctrine.event_listener, event: postUpdate }

