<?php

namespace FS\PaysBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityRepository;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository
{

    public function getPays($first_result, $max_results = 5)
    {
        $qb = $this->createQueryBuilder('pays');
        $qb
            ->select('pays')
            ->addSelect('contienet')
            ->leftJoin('contienet.pays', 'continent')
            ->setFirstResult($first_result)
            ->setMaxResults($max_results);

        $pag = new Paginator($qb);
        return $pag;
    }

}
