admin_groups_index:
    path:     /
    defaults: { _controller: "FSUserBundle:Group:index" }
    methods:  GET

admin_groups_show:
    path:     /{id}/show
    defaults: { _controller: "FSUserBundle:Group:show" }
    methods:  GET

admin_groups_new:
    path:     /new
    defaults: { _controller: "FSUserBundle:Group:new" }
    methods:  [GET, POST]

admin_groups_edit:
    path:     /{id}/edit
    defaults: { _controller: "FSUserBundle:Group:edit" }
    methods:  [GET, POST]

admin_groups_delete:
    path:     /{id}/delete
    defaults: { _controller: "FSUserBundle:Group:delete" }
    methods:  DELETE
